com:
  huyan:
    datasource:
      eurekaclient:
        url: jdbc:mysql://localhost:3306/prophethy?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
        username: root
        password: root

eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name : client