com:
  huyan:
    datasource:
      eurekaclient:
        url: jdbc:mysql://localhost:3306/prophethy?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
        username: debian-sys-maint
        password: 33NfmKUDjW6n5PHD

eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
spring:
  application:
    name : client